[package]
name                   = "eris-deception"
description            = "Deceptive response generation for Eris: Markov chains and Lua"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
authors.workspace      = true

[dependencies]
log.workspace         = true
markov.workspace      = true
mlua.workspace        = true
parking_lot.workspace = true
rand.workspace        = true
