[package]
name                   = "eris-daemon"
description            = "The Eris tarpit daemon (systemd service)"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
authors.workspace      = true

[[bin]]
name = "eris-daemon"
path = "src/main.rs"

[dependencies]
anyhow.workspace         = true
env_logger.workspace     = true
eris-config.workspace    = true
eris-core.workspace      = true
eris-deception.workspace = true
eris-proto.workspace     = true
eris-runtime.workspace   = true
log.workspace            = true
tokio.workspace          = true
tokio-util.workspace     = true
