[package]
name                   = "eris-proto"
description            = "Protocol parsing for Eris: HTTP heads, PROXY protocol, real client IP"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
authors.workspace      = true

[dependencies]
eris-core.workspace = true
httparse.workspace  = true
ipnetwork.workspace = true
log.workspace       = true
ppp.workspace       = true
tokio.workspace     = true
