[package]
name                   = "eris-config"
description            = "Configuration and CLI for Eris"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
authors.workspace      = true

[dependencies]
clap.workspace        = true
directories.workspace = true
eris-core.workspace   = true
ipnetwork.workspace   = true
regex.workspace       = true
serde.workspace       = true
serde_json.workspace  = true
